spring.application.name=cyber
#spring.datasource.url=jdbc:mysql://localhost:3306/authdb
#spring.datasource.username=root
#spring.datasource.password=yourpassword
spring.data.mongodb.uri=mongodb://localhost:27017/mydatabase
#spring.jpa.hibernate.ddl-auto=update
server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yourgmail@gmail.com
spring.mail.password=your_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Custom properties for API keys (used in your code, not standard Spring Boot properties)
custom.google.safebrowsing.api.key=AIzaSyC9eVWHChb0wCGNMTnW5WSkHaVPvgsoOI4
custom.security.virustotal.api-key=175e6c00b6ccca097e4b0aba3989e2687511455ed687ffad108828cdd4b3763b